-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgszW2TYZUcimR4+jD
wPz362AIyUeuOkcmZBe3j7kO/FKgCgYIKoZIzj0DAQehRANCAARghenYD2emjIzz
bfGKXGmKrs+j5d8BOv3AbzrKggo4LWvlMfCva5Z/X+uVHBgdml9jmEZJIlH7QE8q
snok7XDH
-----END PRIVATE KEY-----