# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do    

# ci 환경에 키체인추가
 create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
      )

# 앱스토어 커넥트 연결필요 => match 저장소 접근시
    app_store_connect_api_key(
     key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
     issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
     key_content: ENV['APP_STORE_CONNECT_KEY']
    )

# 해당 git 주소에서 인증서, 프로비저닝 로드
   match(
      git_url: ENV['GIT_URL'],
      storage_mode: "git",
      type: "appstore",
      app_identifier: ["com.teamHY2.HongikYeolgong2"],
      readonly: true,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD']
    )

    sync_code_signing(type: "appstore", 
		      app_identifier: "com.teamHY2.HongikYeolgong2", 
 		      readonly: true)

   new_build_number = latest_testflight_build_number
   version = get_version_number(xcodeproj: "HongikYeolgong2.xcodeproj")
# 빌드버전 증가
    increment_build_number(
	build_number: new_build_number,
	xcodeproj: "HongikYeolgong2.xcodeproj"
)

# 앱빌드
    build_app(scheme: "HongikYeolgong2", export_method: "app-store")

# 테스트 플라이트 업로드
    upload_to_testflight

discord_notifier(
      webhook_url: "https://discord.com/api/webhooks/1295354068981776474/KcvWD1Z20p2qTQdP-5mUTyug4Knw7iJDwhkyqlNCaSrREBgBFYJtDL_DcpN7XmoSG-yz",
      title: "New TestFlight Build Available!",
      description: "새로운 버전 #{version}(#{new_build_number}) 이 TestFlight에 업로드 되었습니다. 🙌",
      success: true,
      fields: [  
        {
          name: "Version",
          value: "#{version}"
        },
        {
          name: "Build",
          value: "#{new_build_number}"
        }
      ]
    )
  end
end
