# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    
     # 인증서 연동
     if is_ci
      create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
  )

    match(
      git_url: ENV['GIT_URL'],
      storage_mode: "git",
      type: "appstore",
      app_identifier: ["com.teamHY2.HongikYeolgong2"],
      readonly: true,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD']
    )
     else
    # 인증서 연동
    match(
      git_url: ENV['GIT_URL'],
      storage_mode: "git",
      type: "appstore",
      app_identifier: ["com.teamHY2.HongikYeolgong2"],
      readonly: true,
      keychain_name: "keychain",
      keychain_password: "123456"
    )
     end

    # 앱스토어 커넥트 연결
    app_store_connect_api_key(
     key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
     issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
     key_content: ENV['APP_STORE_CONNECT_KEY']
   )

    # 빌드버전 증가
    increment_build_number(xcodeproj: "HongikYeolgong2.xcodeproj")

    # 앱빌드
    build_app(scheme: "HongikYeolgong2")
    
    # 테플에 업로드
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
